---
- platform: openweathermap
  api_key: !secret owm_api_key
  monitored_conditions:
    - temperature
- platform: transmission
  host: 192.168.1.55
  monitored_variables:
    - 'current_status'
    - 'download_speed'
    - 'upload_speed'
    - 'active_torrents'
- platform: fitbit
  clock_format: 12H
  monitored_resources:
    - 'body/weight'
- platform: worldclock
  time_zone: Australia/Sydney

- platform: pollen
  zip_code: '94118'
  monitored_conditions:
    - allergy_index_today
    - allergy_index_tomorrow
    - allergy_index_yesterday
- platform: pi_hole
  host: 192.168.1.5:8880
